### ISSUE TITLE
Extracting emojis

### ISSUE THREAD

**Issue by JochenFromm** [github/gemoji#102]
Extracting emojis does not work as described in the Readme at all, neither on Mac OS El Capitan nor on Mac OS Sierra. The command `gemoji extract public/images/emoji` was introduced for 3.0.0.rc1, so the current description does not match the behavior of the version 2.1.0 that is installed currently using `bundle install`. Previously the gemoji gem apparently used `rake emoji` but this does not work either for the [gem version 2.1.0](https://github.com/github/gemoji/releases ). This leaves the user a bit confused 😕  .

**Comment by mislav** [comment]
The README for the master branch only applies to the edge version, of course, which is currently released as 3.0.0.rc1. Yes, previously there was a rake task, but it won't work on macOS Sierra due to changes to its Apple Color Emoji font. Can you try the `gemoji extract` command from 3.0.0 and tell us if it works?

**Comment by JochenFromm** [comment]
I only have Mac OS El Capitan, but my colleagues who use Sierra reported they could not get it to work, probably because of the transition from 2.1.0 to 3.0.0. As a workaround it is possible to download [2.1.0](https://github.com/github/gemoji/releases/tag/v2.1.0) where the emojis are contained in the `images/emoji/unicode` directory. Is it legal to use them, BTW? Extracting emojis from a font and turning them into bitmapped PNG images could cause a [copyright problem]( http://stackoverflow.com/questions/10834811/emoji-copyright).

**Comment by mislav** [comment]
I can't give you any advice about the legality of your decisions. The latest version of gemoji doesn't ship with bitmaps anymore, just with a script to extract them if you desire to do so. What you do with that script is up to you. The script will only work on Sierra and later.
