### ISSUE TITLE
How can we get the emoji images of different skin?

### ISSUE THREAD

**Issue by mopduan** [github/gemoji#103]
I find the code "return if glyph_name =~ /\.[1-5]($|\.)/" of extractor.rb.

If I want to export the emoji images of different skin, how to modify the code of extractor.rb?  

Thanks a lot!

**Comment by mislav** [comment]
That's in the works in #101. In the meantime, the only workaround is to change the code manually. Sorry for the inconvenience!

**Comment by mopduan** [comment]
Thanks a lot!
