### ISSUE TITLE
error extracting emoji on El Capitan

### ISSUE THREAD

**Issue by kejadlen** [github/gemoji#105]
When I run `bundle exec gemoji extract public/images/emoji`, I get the following error:

```
.../.bundle/gems/gemoji-3.0.0.rc1/lib/emoji/extractor.rb:18:in `initialize': No such file or directory - /System/Library/Fonts/Apple Color Emoji.ttc (Errno::ENOENT)
```

`ls`ing the `Fonts` directory reveals that on my machine, the font has an extension of `.ttf` rather than `.ttc`. Logging an issue here rather than creating a PR since I don't know if this is a typo or if some machines have the font under `.ttc` instead of `.ttf`.

**Comment by mislav** [comment]
Please [read the documentation](https://github.com/github/gemoji#extract-images). You can only use this command on Sierra. There's no sense in extracting the emoji on an older OS because you will end up with outdated images of emoji.

**Comment by kejadlen** [comment]
Oops, apologies - saw the extract command, but not that it was scoped to Sierra.
