### ISSUE TITLE
find some issues in emoji.json

### ISSUE THREAD

**Issue by mopduan** [github/gemoji#106]
When I use emoji.json, I found some emoji code may be not correctly, such as: keycap from 0 to 9.

There are a screenshot: 
![emoji](https://cloud.githubusercontent.com/assets/675025/19882423/9e0aa658-a048-11e6-8cbe-f372f03a2b58.png)

Thanks a lot!

**Comment by mopduan** [comment]
sorry, It's my fault, please close this issue, thanks!

**Comment by mislav** [comment]
No worries! Did you know you can close the issue yourself? 😉 

Also, please be aware that the native display of keycap emoji in current version of Google Chrome is broken. It's a known issue.

<img width="210" alt="screen shot 2016-11-01 at 11 36 23 am" src="https://cloud.githubusercontent.com/assets/887/19887247/a20f98d8-a027-11e6-852e-5148ccaef595.png">

**Comment by mopduan** [comment]
You are my hero!! Thank you!!
