### ISSUE TITLE
cannot export the "26D1.png"

### ISSUE THREAD

**Issue by mopduan** [github/gemoji#107]
Sorry, I have a lot of questions, so I feel may be I was a trouble-maker (cry emoji) now.

But I found can't export "26D1.png".

Thanks!

**Comment by mislav** [comment]
Which emoji.json are you looking at? I'm [seeing it right here](https://github.com/github/gemoji/blob/f394c85d80b3ed7a1146683a72c13e4e8985f6ce/db/emoji.json#L2929).

**Comment by mopduan** [comment]
The emoji.json I used is [emoji.json](https://github.com/github/gemoji/blob/f394c85d80b3ed7a1146683a72c13e4e8985f6ce/db/emoji.json#L2929), My question is, After exec "bundle exec gemoji extract public/images/emoji", can't found the "26d1.png", but the emoji code "26d1" is in emoji.json.

**Comment by mislav** [comment]
The same command does extract `26d1.png` for me; I've just tested on macOS 10.12.1. What version are you trying it on?

**Comment by mopduan** [comment]
macOS 10.12.1, I got the reason, because I use the code [fork of gemoji with skin tone](https://github.com/s0meone/gemoji/) , may be there are some issues in this fork.
