### ISSUE TITLE
`bundle exec gemoji extract` doesn't work for the RubyGems version

### ISSUE THREAD

**Issue by matthewheath** [github/gemoji#112]
# What I expected to happen
- Add `gem "gemoji"` (v2.1.0) to my Gemfile
- Run `bundle exec gemoji public/images/emoji`
- It to "just work"

# What actually happened
- Add the `gem "gemoji"` to my Gemfile
- Ran `bundle exec gemoji public/images/emoji`
- Error returned was `bundler: command not found: gemoji`

# Workaround
Use the gem directly from the GitHub repo (repo version is 3.0.0.rc1)

**Other information:**
Unsure if this would impact it but my Ruby version is 2.3.1 and I'm running Rails 5.

**Comment by mislav** [comment]
Sorry about that! `gem "gemoji", ">= 3.0.0.rc1"` is the correct workaround, since the stable version of the gem doesn't yet include the `gemoji` command. This will be fixed when v3.0.0 hits stable, which is long overdue by now, and is my fault.

Thanks for reporting!
