### ISSUE TITLE
New line problem?

### ISSUE THREAD

**Issue by kirkins** [github/gemoji#121]
I'm writing the following in my code without new lines:

`:eu: :romania: :portugal: :it: :es: :fr:`

But each emoji displays on a [new line](https://kirkins.github.io/javascript/2017/02/28/euroromcom-course.html).

**Comment by mislav** [comment]
This is because your CSS on the site defines a `display: block` rule for all `<img>` tags. This means that your CSS defines all images to be one per line.

Closing as an issue with your styles, not as a gemoji bug.
