### ISSUE TITLE
🏋️ Person Lifting Weights doesn't get parsed correctly

### ISSUE THREAD

**Issue by kirkas** [github/gemoji#122]
🏋️  can be `\U+1f3cb\U+fe0f` or `\U+1f3cb`, the later doesn't get parsed by gemoji

`\U+1f3cb\U+fe0f` -> get parsed to  `:weight_lifting_man:`
`\U+1f3cb` -> fail to get parsed

I think it's because there's actually two implementations 
http://emojipedia.org/weight-lifter/ added to Emoji 1.0 in 2015.
http://emojipedia.org/man-weight-lifting/ added to Emoji 4.0 in 2016.

**Comment by zhufengnodejs** [comment]
:smile :sob:

**Comment by mislav** [comment]
Thanks for letting us know! This now works:

```
ruby -Ilib -remoji -e 'p Emoji.find_by_alias("weight_lifting_man").unicode_aliases.map { |a| Emoji::Character.hex_inspect(a) }'
["1f3cb", "1f3cb-fe0f", "1f3cb-fe0f-200d-2642-fe0f"]
```

You can see that both forms with and without `fe0f` are now recognized.
