### ISSUE TITLE
cant parse man shrugging 🤷‍♂ 

### ISSUE THREAD

**Issue by omaijdot** [github/gemoji#132]
Hi,

I tried to use gemoji to take the unicode then display with twemoji, and react-emoji as svg file. unfortunately for the 2 unicode like man_shrugging or woman_student. it is failed to load properly. please refer to imaage attached. May i know how to deal with 2 unicode to parse as 1 emoji?
![image](https://user-images.githubusercontent.com/1439453/30682616-d910c8f2-9edc-11e7-9be7-c7f940ce3219.png)

**Comment by mislav** [comment]
Sorry, but gemoji doesn't facilitate parsing unicode sequences from streams of text. You'll have to figure this one out on your own. You haven't shared any of your parsing code, so we can't tell what you're doing wrong.

Here's roughly how we do it on GitHub.com:

```rb
VARIATION_SELECTOR_15 = "\u{fe0e}".freeze
ZERO_WIDTH_JOINER = "\u{200d}".freeze
SKIN_TONE_MODIFIERS = "\u{1F3FB}".."\u{1F3FF}"

# Index of characters that, when appended after an emoji, trigger a
# condition when we will avoid wrapping the emoji in `<g-emoji>`.
modifier_chars = [VARIATION_SELECTOR_15, ZERO_WIDTH_JOINER].concat(SKIN_TONE_MODIFIERS.to_a)
MODIFIER_CHAR_MAP = modifier_chars.each_with_object({}) { |char, map| map[char] = true }

def unicode_emoji_filter!(text)
  text.gsub!(unicodes_pattern) do |unicode|
    previous_character = $`[-1]
    next_character = $'[0]
    if ZERO_WIDTH_JOINER == previous_character || MODIFIER_CHAR_MAP.key?(next_character)
      unicode
    else
      emoji = Emoji.find_by_unicode(unicode)
      "<g-emoji alias='#{emoji.name}' fallback-src='#{emoji_url(emoji.name)}' ios-version='#{emoji.ios_version}'>#{unicode}</g-emoji>"
    end
  end
end

def unicodes_pattern
  @unicodes_pattern ||= Regexp.new(emoji_unicodes.sort_by(&:length).reverse.map { |u| Regexp.escape(u) }.join("|"))
end

def emoji_unicodes
  Emoji.all.flat_map(&:unicode_aliases)
end
```

**Comment by omaijdot** [comment]
okie2.. thank you for your answer..  👍
