### ISSUE TITLE
Category-Emoji.plist no longer exists on macOS 10.13+

### ISSUE THREAD

**Issue by meyer** [github/gemoji#133]
The `db:generate` rake task is broken on macOS 10.13 and up because (I might be wrong on this) it looks like Apple started using a private framework to get emoji data in the Character Palette. I did some junior-level spelunking with `class-dump` but couldn’t figure out how to use the private framework. The best solution that I can think of at the moment is to cross-reference the output of `Apple Color Emoji.ttc` with unicode CLDR data.

**Comment by mislav** [comment]
Thank you for bringing this to our attention. 🙇

**Comment by mislav** [comment]
https://github.com/github/gemoji/pull/155
