### ISSUE TITLE
Cricket emoji missing

### ISSUE THREAD

**Issue by dkasak** [github/gemoji#134]
It appears the [cricket](https://emojipedia.org/cricket/) 🦗 emoji is missing from `emoji.json`. Maybe that has something to do with 🏏  being present and its alias being "cricket"?

**Comment by Crissov** [comment]
No, it has to do with Gemoji not having been updated to support Unicode 10.0 and Emoji 5.0, both released in May/June 2017. The final Apple graphics Github relies upon are available since iOS 11.1 was released in very late October 2017 (with minor updates since then in 11.2).

**Comment by mislav** [comment]
We now support Unicode 11 https://github.com/github/gemoji/pull/155
