### ISSUE TITLE
Unicode 11.0 / Emoji 11.0 (2018)

### ISSUE THREAD

**Issue by Crissov** [github/gemoji#139]
While Gemoji currently does not even support Unicode 10.0 / Emoji 5.0 yet #134 #136, the 2018 [Emoji 11.0 data files](http://unicode.org/Public/emoji/11.0/) have already been published with a full release being scheduled for June. 

Apple will probably not release iOS and macOS updates with new emoji graphics before very late in 2018, but since Apple lately seems to be pushing against other vendors reusing their graphics, you might as well update emoji.json now and adopt [Google Noto](https://github.com/googlei18n/noto-emoji/), [Twitter Twemoji](https://github.com/twitter/twemoji/) or [Emojione](https://github.com/emojione/emojione/)/[Emojitwo](https://github.com/EmojiTwo/emojitwo/) (which were intended to be supported anyway #72). Twitter in particular was very early to release an update in 2017.

**Comment by annainfo** [comment]
Google Noto would be nice. And switch fonts to Noto too. Having a visible difference between I and l makes communication easier.

**Comment by mislav** [comment]
We now support Unicode 11 https://github.com/github/gemoji/pull/155

**Comment by Crissov** [comment]
Meanwhile, Unicode 12.0 and Emoji 12.0 have been released in March.

**Comment by rriemann** [comment]
Coming from https://github.com/jekyll/jemoji/ . Will there be a release of gemoji anytime soon?

**Comment by mislav** [comment]
We now also support Unicode 12 https://github.com/github/gemoji/pull/159

Yes there will be a release soon.
