### ISSUE TITLE
Any suggestions for linux users?

### ISSUE THREAD

**Issue by binarymason** [github/gemoji#143]
> To obtain image files as fallbacks for browsers and OS's that don't support emoji, run the gemoji extract command **on macOS Sierra or later**: :cry: 

If there's a relatively easy win for this, I'd be happy to add to the documentation.

Thank you!

**Comment by binarymason** [comment]
Going to close this.  Here's the solution I ended up running with that still supports use case of looking up emoji by `shortname` and returning an image.

Using:
https://github.com/twitter/twemoji

Download this file:
https://github.com/iamcal/emoji-data/blob/master/emoji_pretty.json

Using emoji file, you can now look up by  `shortname` then use [twemoji ](https://github.com/twitter/twemoji) to get image tag from their CDN.  To have custom emoji support, make another emoji file and reference static images.

<hr>
Admittedly not the best code, but at least working example :sweat_smile: : 

https://github.com/charlottedevs/slackerboard/blob/master/src/emoji.js

**Comment by HorlogeSkynet** [comment]
Hi @binarymason ! Maybe a bit late, but [here](https://github.com/HorlogeSkynet/SgEExt) is what I ended up building, for ~~us~~ non macOS users.

Related to #114 (just in case some wanderers got here or there).

Bye :wave:
