### ISSUE TITLE
vertical-align for <g-emoji> tag seems not correct

### ISSUE THREAD

**Issue by kenmick** [github/gemoji#145]
The `vertical-align` is set as `middle` which cause `emoji` and text are not aligned in the same line. Please check the following screenshot.
![gemoij-vertial-align](https://user-images.githubusercontent.com/10039224/44072139-ae1f223a-9fbf-11e8-9948-abb0fd85655e.png)

**Comment by mislav** [comment]
Hi, it looks like you're trying to report an issue with how GitHub.com uses this library, not this library itself. For issues with GitHub.com, please contact support@github.com. Thank you!
