### ISSUE TITLE
:simple_smile: missing?

### ISSUE THREAD

**Issue by dmalan** [github/gemoji#146]
Just wanted to check if `:simple_smile:`, which is listed among the **People** at https://www.webfx.com/tools/emoji-cheat-sheet/, is known to be missing? Is it perhaps supposed to map to `:slightly_smiling_face:`, per https://api.github.com/emojis?

Thanks for the handy gem!

**Comment by mislav** [comment]
Yes, gemoji doesn't have `:simple_smile:`. Our aliases for emoji characters are listed in https://github.com/github/gemoji/blob/master/db/emoji.json and don't necessarily correspond to aliases used for emoji characters on other sites/libraries. Also, this library hasn't been brought up to date with the latest Unicode standard yet #136
