### ISSUE TITLE
How do you remove emojis?

### ISSUE THREAD

**Issue by svpersteve** [github/gemoji#160]
We had some that were added during testing and these need removing, but it's not clear how I can do that. Removing the image files from assets just leaves a missing image icon where the emoji was.

**Comment by mislav** [comment]
I'm not sure what you mean! You've addded a custom emoji, presumably by doing something like:

```rb
require "gemoji"
Emoji.create("hello")
```

And then you created the `hello.png` image in your app, correct? So to remove the emoji, I think it's enough to delete `hello.png` and to remove the `Emoji.create` line.

**Comment by svpersteve** [comment]
We've added some custom emojis before with `png` images for each of them. I've removed the `png` images but there's still an Emoji record in the database that's not being initialised in `config/initializers/emoji.rb`, it's just in the database and I can find it with `Emoji.all` but can't seem to remove it from that list. 

The options the emojis still show up in are rendered like this:
```
          - Emoji.all.each do |emoji|
            = image_tag "emoji/#{emoji.image_filename}", :class => "emoji", :title => emoji.name.titleize
```

**Comment by mislav** [comment]
The "feelsgood", "finnadie" and other custom emojis missing in your screenshot were a part of `Emoji.all` in the latest gemoji release but are all gone now in the master branch and will be removed in the next gemoji release. The next version of our library will ship with no custom emoji whatsoever. You will just have to hold out until the next release (and probably keep the pngs until then). Thank you!

**Comment by svpersteve** [comment]
Lovely, thank you! 🙏

**Comment by Smartcreasy** [comment]
Hello friends any one have any sourse code for this pleas give your github link I want to host in website
