### ISSUE TITLE
Split out maintained emoji.json file?

### ISSUE THREAD

**Issue by fdw** [github/gemoji#162]
I wrote an [emoji picker for rofi](https://github.com/fdw/rofimoji), and so I also maintain a list of emojis. Since there are no official aliases, rofimoji also doesn't have any, which is not ideal.

I'd like to use your emojis.json file for this, and I think the license allows this. However, I'd rather not depend on some file in some folder, but would much rather have a separate project. Have you thought about splitting the `db` folder off as a separate project for others to use?
This way, it would be much cleaner and maintenance of the aliases (and the other data) could be comunity-driven and concentrated on one repo.

**Comment by koddsson** [comment]
Hey @fdw 👋 

We currently don't have any plans to split the `emoji.json` out as a separate project.

You could always curl the `emoji.json` straight from GitHub but if we ever move the file that will break for you 😬
