### ISSUE TITLE
Where do tags come from?

### ISSUE THREAD

**Issue by YuriGor** [github/gemoji#167]
There are no keywords in vendor/unicode-emoji-test.txt
I also cannot find machine-readable emoji list with tags at unicode.org
The best source I found is keywords from this page:
https://unicode.org/emoji/charts/emoji-list.html
But looks like tags in db/emoji.json do not match these keywords.
I tried to look into the code, but found no signs of external resources usage.

I ask about tags because I need them, but I see a lot of emojis do not have tags.
So I suspect  emoji.json is not fully generated using external resources but maintained manually? 

So should/may I contribute by adding missing tags?

**Comment by mislav** [comment]
Tags are invented by the maintainers of this project to increase emoji searchability, especially in GitHub web UI emoji autocompleter. We add tags as we see fit, e.g. `raised_eyebrow` will also have the "suspicious" tag, and several emoji that are commonly used to express laughter have the "haha" tag.

You are welcome to suggest tags. However, keep in mind:
* tags should only be simple words that users might commonly search for in English,
* not too many emoji should share a tag (my recommendation is 5 emoji maximum).

Which ones did you plan to add?

**Comment by YuriGor** [comment]
well, I'll better not try to change it here, but fork it for my use case. I need more than 5 emoji per tag, for example "transport", "ground transport", "air transport" etc.
