### ISSUE TITLE
Raising errors during use

### ISSUE THREAD

**Issue by duartemvix** [github/gemoji#174]
I'm afraid this is was not an error previously but I'm assuming this library hasn't been updated recently.

The EmojiHelper module indicated on the Readme docs is raising errors during its execution.

```ruby
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end
```

Error is a NoMethodError thrown by Ruby reading the h(content) method.

```NoMethodError (undefined method `h' for #<BlogsController:0x00007f4a2e1f7488>):```

**Comment by mislav** [comment]
Hi, it looks like you are including the EmojiHelper module into your controller?

The EmojiHelper as offered in the example is meant to only be used in ERB templates; e.g. in Rails view templates. There, the methods `h()` and `html_safe` are defined. They won't be available in controllers.

In any case, the method in the example is meant to be only that: an example. You should adapt it to fit your own application.

**Comment by duartemvix** [comment]
That was really a misuse by myself.

But, thanks, Mislav. Please keep up what seems to be a great gem.
