### ISSUE TITLE
How should users apply skin tone modifiers?

### ISSUE THREAD

**Issue by wearhere** [github/gemoji#178]
I've searched through issues and examined the DB and from what I can tell, the library currently reports what emojis can accept a skin tone modifier but doesn't actually provide the modified variants, but rather, only/always the base emoji. That's fine, it [seems like](https://crunchybagel.com/using-emoji-skin-tone-modifiers-in-swift/) it should be easy to produce the variants by appending the modifiers to the base.

Unfortunately, this fails for all of the emojis that have `U+FE0F VARIATION SELECTOR-16` appended. As an example, when copying "✋" and "🖐️" out of `emojis.json`, I can do "✋" + "🏻" and get "✋🏻", but "🖐️" + "🏻" results in "🖐️🏻".

It [looks like](https://github.com/github/gemoji/issues/163) this library intentionally includes the selector for certain emojis. Moreover, trying to drop the selector, then append the modifier to the remaining [unicode scalars](https://developer.apple.com/documentation/swift/string/unicodescalarview), results in correctly modified emoji for only _some_ of the results ("🖐️" yes; "👨‍🍳" no).

Do you folks have recommendations on how to apply the modifiers?

**Comment by wearhere** [comment]
I've come up with an algorithm to apply the modifiers that seems to work for all current emoji. When I say "unicode scalars" below, this is [Swift's terminology](https://developer.apple.com/documentation/swift/string/unicodescalarview); I _think_ it's equivalent to JavaScript's codepoints, not sure what they're called in Ruby. The algorithm:

1. First, sanitize the emoji:
  a. if it has a variation selector as its second scalar and is longer than two scalars, remove that selector. Example problematic emoji: "🕵️‍♂️"
  b. only allow a variation selector at the end of the emoji if the emoji contains a zero-width joiner (`U+200D`), otherwise remove it. Example problematic emoji: "🖐️"

2. Now, apply the modifier: insert it as the second scalar. This is the same as appending it for emoji that were only a single scalar to start e.g. "🖐️" (ignoring any variation selector), but appending fails for emoji like "💆‍♂️" (emoji that contain joiners? Maybe the modifier should really be inserted just prior to the joiner rather than as the second scalar per se 😬 )

This algorithm is just based on heuristics though&mdash;starting with "just append the modifier to the base", then examining examples ƒor which that didn't work and figuring out how I would need to transform them to make them work. [Those examples](https://gist.github.com/wearhere/ac1b03f64224c035b51c5b4b473b9aec). Would love to ground this in some spec.

**Comment by wearhere** [comment]
Ok I deleted my previous comment talking about trial-and-error since I found [the spec](https://unicode.org/reports/tr51/#Diversity). In particular, it says:

> an emoji modifier must immediately follow that base emoji character

and

> Emoji presentation selectors are neither needed nor recommended for emoji characters when they are followed by emoji modifiers, and should not be used in newly generated emoji modifier sequences; the emoji modifier automatically implies the emoji presentation style.

I think that suggests processing emojis like [this](https://gist.github.com/wearhere/97528e81da82387d5fa4aa788856cdc1). You're welcome to adopt that implementation for this library if you like, tried to heavily comment and test it both from the perspective of "does this format correctly" _and_ "does this render correctly (on Apple platforms, at least)".

One note about non-Swift implementations is that you'll probably need to look up the scalar (codepoint) properties (`isVariationSelector`, `isEmojiModifier`, `isEmojiModifierBase`) from an external lookup table. I'm pretty sure that unicode.org provides such and I believe this library already parses some of them.

**Comment by wearhere** [comment]
The Gist linked from my previous comment doesn't support applying different modifiers to each person in a [multi-person grouping](https://unicode.org/reports/tr51/#Multi_Person_Groupings). I'm currently adding support for that and will probably publish the result as a Swift package rather than continue to add to the Gist.

In the meantime, I'd like to call out a limitation of [the algorithm](https://gist.github.com/wearhere/97528e81da82387d5fa4aa788856cdc1#file-playground-swift-L39) in the Gist: it won't work for 👭, 👫, and 👬. That's because those emojis consist of a single scalar, whereas applying different modifiers to each person in the grouping would require representing the groupings as a ZWJ sequence. This means that we have to convert those emojis into a sequence before applying the algorithm:

```swift
extension String {
    var modifiableBySkinTone: String {
        switch self {
        case "👭": return "\u{0001F469}\u{200D}\u{0001F91D}\u{200D}\u{0001F469}"
        case "👫": return "\u{0001F469}\u{200D}\u{0001F91D}\u{200D}\u{0001F468}"
        case "👬": return "\u{0001F468}\u{200D}\u{0001F91D}\u{200D}\u{0001F468}"
        default: return self
        }
    }
}
```

I hoped to submit some sort of PR to add those "sequence forms" to this project's database, the idea being that a capable platform¹ could only ever store and display those versions of 👭, 👫, and 👬 and so avoid having to convert the single-scalar versions in the process of applying skin tones.

Unfortunately, these sequences only render as single characters when they contain modifiers, at least on macOS 10.15.4. Apple probably didn't bother adding code to make the base sequences render given that they can display the single-scalar versions instead.

-----------------
¹Supporting Emoji 12.0, which I think is when the sequence forms were added, per [the spec](https://unicode.org/reports/tr51/#multiperson_skintones)—whereas the single-scalar emoji date back to Emoji 6.0.

**Comment by wearhere** [comment]
Two more gotchas I've found while working on multi-person groupings:

Firstly, the [basic algorithm](https://gist.github.com/wearhere/97528e81da82387d5fa4aa788856cdc1#file-playground-swift-L39) may return results that won't actually render in cases where platforms haven't generally added support for rendering all the different variants. In these cases, the database correctly omits `skin_tones` and so the fix is to simply skip trying to modify such emoji.

More problematic is that `skin_tones` may be `true` in cases where only _some_ platforms will render the different variants. This is because "in some circumstances, display of an emoji modifier… should be suppressed", [per the spec](https://unicode.org/reports/tr51/#Diversity_Implementations). As an example, Apple depicts 🏂 without any visible skin whereas Android shows skin. This means that my Swift implementation (for use in iOS) should return no variants for 🏂 whereas implementations for other platforms would need to behave differently.

**Comment by mislav** [comment]
Thanks for sharing your finding so far!

I am unable to provide advice on how to implement support for skin tone modifiers on top of gemoji since I've never done it. The library does report which emoji supports skin tone modifiers, but intentionally does not yet provide any facilities to generate or parse emoji with skin tones because we haven't figured out proper support for this yet, so the implementation is left to the users.

**Comment by mislav** [comment]
With https://github.com/github/gemoji/pull/165 merged, you can now call the `raw_skin_tone_variants` method on an emoji character to get a set of 5 unicode sequences that have each of the skin tone modifiers inserted at the right place.
