### ISSUE TITLE
Aliases for Piñata

### ISSUE THREAD

**Issue by stone-zeng** [github/gemoji#180]
https://github.com/github/gemoji/blob/5361b5639f004a11221fb34dad272d0093ec3239/db/emoji.json#L13394-L13405

The aliase for Piñata is `pi_ata` as shown above. Is it correct? I think `pinata` may be better?

**Comment by mislav** [comment]
That's definitely a bug. You are welcome to submit a pull request!

**Comment by Mk1206mk** [comment]
https://github.com/desktop/desktop/blob/f874adc68d304f18dc0df1ec83070b5d81045cdf/app/src/highlighter/globals.d.ts
