### ISSUE TITLE
Import Emoji 13.1

### ISSUE THREAD

**Issue by xPaw** [github/gemoji#188]
https://emojipedia.org/emoji-13.1/

**Comment by mchan2jjang** [comment]
fj

**Comment by mchan2jjang** [comment]
hjfgjh

**Comment by mchan2jjang** [comment]
gfhjfhgfghhjdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhfhhh

**Comment by mchan2jjang** [comment]
jhfgjafgpihklnWGsdvc8HIPK3REFADZ

**Comment by mchan2jjang** [comment]
ASFH;;AHSJFDJHSDAHDDJDSH'O

**Comment by mchan2jjang** [comment]
🎎🧶

**Comment by mislav** [comment]
Fixed in 64cd0e9ccf6e9f53531bded589d8cd0aab006f14
