### ISSUE TITLE
Choose wether to type out emojis with an underscore or with a space

### ISSUE THREAD

**Issue by M3Evo** [github/gemoji#208]
Hello, 
I would like to know if it is possible to type out long emojis with an underscore instead of space.
For example, I want  `:smiley_cat:`  instead of  `:smiley cat:`, since I'm more used to it that way.
Thank you.

**Comment by voicelessbellow** [comment]
i want 😺 ":smiley_cat"

**Comment by dzimidrol5** [comment]
w

**Comment by mislav** [comment]
I do not understand the question fully, but you can type out `:smiley_cat:` to result in "😺". In fact, spaces instead of underscores will not work. All emoji aliases in this library are joined by underscores, not spaces.
