### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by parkr** [github/gemoji#213]
Hello friends!

I was wondering if there was any interest in releasing a final v4. If not, what are the open questions/concerns/bugs?

I see that @koddsson release RC3 a few months ago, so we should hopefully be close!

Thanks!

**Comment by parkr** [comment]
Hey @mislav, are you hoping to include https://github.com/github/gemoji/pull/165 in the v4.0 release?

**Comment by rriemann** [comment]
Hi all!

Any updates on the 4.0 release?

**Comment by bewuethr** [comment]
Looks like it's been [released](https://github.com/github/gemoji/releases/tag/v4.0.0)!

**Comment by mislav** [comment]
Thanks for your patience, all ❤️

**Comment by parkr** [comment]
Thank you so much, @mislav! ❤️
