### ISSUE TITLE
Beginless Ranges are not supported in ruby '<2.7'

### ISSUE THREAD

**Issue by kyntk** [github/gemoji#254]
- ruby version: 2.6.10
- version: gemoji 4.0.0

An error was caused by that beginless ranges are not supported in ruby '<2.7'.
Is ruby 2.6 or lower no longer supported?

```
gemoji-4.0.0/lib/emoji/character.rb:54: syntax error, unexpected ..., expecting ']'
            raw_normalized[...idx] + modifier + raw_normali...
                           ^~~
```

**Comment by mislav** [comment]
We stopped testing in Ruby 2.6 due to it being EOL (end-of-life). However, it wasn't intentional to introduce a change that is only supported from Ruby 2.7. You are welcome to submit a PR that adds `0` as the beginning to the range!

**Comment by perlun** [comment]
@mislav @kyntk I gave it a try since I saw this also in my own CI runs (https://github.com/perlun/perlun.eu.org/pull/39). Here's my attempt at a PR: https://github.com/github/gemoji/pull/255

**Comment by mislav** [comment]
Thank you! Fixed in https://github.com/github/gemoji/commit/33caddce20380b7ff7fe96f500bec9d383cd4df9
