### ISSUE TITLE
Emoji-quantum-computers 

### ISSUE THREAD

**Issue by Grant1tnarg** [github/gemoji#259]
https://anchor.fm/thatblogger/call/i-ccq2g

**Comment by Grant1tnarg** [comment]
💡🐈‍⬛🖤🖥️👻🙉🔭🥜✌️🌎💗

**Comment by PollyChangkt** [comment]
取消訂閱。unsubscribe.

Grant1tnarg ***@***.***>於 2023年2月9日 週四，05:05寫道：

**Comment by Grant1tnarg** [comment]
I've written a few books on emoji Quantum computing and bio computer
technology and I'm curious which way the audience would like to go?

**Comment by Grant1tnarg** [comment]
10:46 AM

X

100%

Poll

Save

Ask your listeners a question on Spotify.

I've written a few books on emoji Quantum computing and bio computer
technology and I'm curious which way the audience would like to go?

Poll choices

Bio-Computers

Emoji-quantum-computers
Guest

FMRI beings?

X

X

X

Option 4

Option 5

+ Add Option
