### ISSUE TITLE
How to escape emoji?

### ISSUE THREAD

**Issue by onmyway133** [github/gemoji#89]
Hi, I'm using your gemoji to create this https://github.com/onmyway133/emoji, to help myself search emoji better.

It 'd be great if I can display like `: star :` (I add spaces here to that it is not converted to emoji) so that I can copy-paste it right away. I try to escape with back tick, but it always shows as "⭐ "

Thanks

**Comment by mislav** [comment]
Hello @onmyway133. You should definitely be able to use backticks to escape emoji, like shown here:

```
emoji | alias | description
---|---|---
:star: | `:star:` | it's a star
```

This gets rendered as:

emoji | alias | description
---|---|---
:star: | `:star:` | it's a star

What result do you get instead?

**Comment by onmyway133** [comment]
@mislav Hi, thanks for response. I get `:star:` (the actual star emoji inside backtick). I use `table, tr, td`, is that the reason ?

**Comment by mislav** [comment]
Ah yes, if you use actual `<table>` HTML tags, you would need to use `<code>:star:</code>` instead of backticks. But yes, you should go with Markdown table instead because they are easier to write and maintain. 😉

**Comment by bartonstanley** [comment]
Based on [this post](https://stackoverflow.com/questions/50657698/how-can-i-stop-github-from-rendering-emojis-in-markdown) I was able to resolve this in my case by using the hex encoded character entity for zero-width space: &#8203;  In my case the "8)" portion of "(7 & 8)" was being rendered as the "cool" emoji.  Inserting a zero-width space between the "8" and the right parenthesis did the trick.  Like this:  "(7 & 8&amp;#8203;)".

FWIW, [this post](https://stackoverflow.com/questions/11392312/zero-width-non-breaking-space) mentions other characters that might also do the trick. See the comment by `davidcondrey`.
